version: '3.8'

services:
  backend:
    # Option 1: Build locally from Dockerfile (uncomment below and comment image line)
    # build: .
    # Option 2: Use published Docker Hub image (recommended)
    image: ishantkohar/anchor-backend
    ports:
      - "9066:9066"
    network_mode: host
    # Use production environment configuration for Docker
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    # Enable connection to host services (OpenAI proxy)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15
    network_mode: host # for testing locally
    environment:
      - POSTGRES_DB=reasoning_db
      - POSTGRES_USER=reasoning_user
      - POSTGRES_PASSWORD=reasoning_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    # Enable connection to host services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reasoning_user -d reasoning_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      

  mcp-server:
    image: ishantkohar/anchor-backend
    # build:
    #   context: .
    #   network: host
    ports:
      - "8787:8787"
    network_mode: host
    # Override the default command to run MCP server
    command: python run_mcp_server.py --transport sse --host 0.0.0.0 --port 8787
    # Use same environment configuration
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads  # Shared uploads directory
    # Enable connection to host services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8787/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8083:8080"
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  default:
    name: reasoning_network 